# Settings are for a RealSense D435 sensor written by Lefteris kotsonis.
# TODO: Modify the settings for the ZED2i camera.
sensor_processor:
  ros__parameters:
    type: structured_light
    cutoff_min_depth: 0.35
    cutoff_max_depth: 29.0
    normal_factor_a: 0.000611
    normal_factor_b:  0.003587
    normal_factor_c: 0.3515
    normal_factor_d: 0
    normal_factor_e: 1
    lateral_factor: 0.01576
